Update versioneer.py
change SaferConfig Parser to RawConfigParser: The AttributeError: module 'configparser' has no attribute 'SafeConfigParser' indicates that you're trying to use the SafeConfigParser class from the configparser module, which has been deprecated and removed in newer Python versions (3.2 and later). The suggestion to use RawConfigParser is because SafeConfigParser was a specific mode of the ConfigParser class that enabled more strict parsing of configuration files, while RawConfigParser (now the default) allows for a more loose interpretation